name: qrcode_scanner
description: "A qr/barcode scanner made by vustron."

publish_to: 'none'

version: 1.0.6+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lucide_icons_flutter: ^1.2.6
  fluentui_system_icons: ^1.1.257
  cupertino_icons: ^1.0.8
  page_transition: ^2.1.0
  flutter_animate: ^4.3.0
  flutter_launcher_icons: ^0.14.1
  hooks_riverpod: ^2.5.4
  flutter_screenutil: ^5.9.3
  toastification: ^2.3.0
  lottie: ^3.3.0
  equatable: ^2.0.7
  mobile_scanner: ^3.5.5
  audioplayers: ^5.2.1
  sqflite: ^2.3.2
  nanoid: ^1.0.0
  path_provider: ^2.1.2
  path: ^1.8.3
  qr_flutter: ^4.1.0
  share_plus: ^10.1.4
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.8
  build_runner: ^2.4.13
  husky: ^0.1.7
  fpdart: ^1.1.1
  test: ^1.25.7
  stack_trace: ^1.11.1
  logger: ^2.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/sounds/
    - qrcode.db

# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  image_path: "assets/icons/qr_code_icon.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/icons/qr_code_icon.png"
  adaptive_icon_background: "#ffffff"

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: "assets/icons/qr_code_icon.png"

