name: qrcode_scanner
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  page_transition: ^2.1.0
  flutter_animate: ^4.3.0
  flutter_launcher_icons: ^0.14.1
  fluentui_system_icons: ^1.1.257
  intl: ^0.19.0
  hooks_riverpod: ^2.5.4
  flutter_screenutil: ^5.9.3
  toastification: ^2.3.0
  shared_preferences: ^2.3.3
  flutter_form_builder: ^9.5.0
  form_builder_validators: ^11.0.0
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  dio: ^5.7.0
  envied: ^1.0.0
  lottie: ^3.3.0
  connectivity_plus: ^6.1.1
  equatable: ^2.0.7
  backdrop: ^0.9.1
  mobile_scanner: ^3.5.5
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.8
  build_runner: ^2.4.13
  husky: ^0.1.7
  fpdart: ^1.1.1
  test: ^1.25.7
  stack_trace: ^1.11.1
  logger: ^2.5.0
  envied_generator: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - secret.env
    - assets/sounds/

# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  image_path: "assets/icons/vustron-icon.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/icons/vustron-icon.png"
  adaptive_icon_background: "#000000"

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#000000"
  image: "assets/icons/vustron-icon.png"

